import { LegalSection, LegalShell } from './LegalShell';

const LAST_UPDATED = '25 July 2026';

export default function TermsPage() {
  return (
    <LegalShell title="Terms of Service" lastUpdated={LAST_UPDATED}>
      <p>
        These terms cover your use of Vedic Sky Observer, including the free readings offered through
        the gift pages. By using the service you accept them.
      </p>

      <LegalSection heading="What the service is">
        <p>
          Vedic Sky Observer calculates sidereal (Lahiri) astrological charts from birth data and
          presents interpretations, some of which are generated by an AI model. Readings are offered
          for reflection and interest.
        </p>
        <p>
          They are <strong>not</strong> professional advice. Do not rely on them for medical,
          psychological, legal, financial, or other professional decisions. If you need that kind of
          help, speak to a qualified professional.
        </p>
      </LegalSection>

      <LegalSection heading="Eligibility">
        <p>
          You must be at least 18 years old. You may submit birth details only for yourself, or for
          someone who has asked you to.
        </p>
      </LegalSection>

      <LegalSection heading="Free readings">
        <p>
          Free readings are a gift, not a purchase, and we may limit how many we prepare each day or
          pause them entirely. A reading is prepared only after you confirm your email address by
          clicking the link we send. We aim to deliver promptly but do not guarantee a delivery time.
        </p>
        <p>
          One request per email address per reading. Requests that appear automated may be discarded.
        </p>
      </LegalSection>

      <LegalSection heading="Accuracy of what you give us">
        <p>
          Charts are only as accurate as the birth date, time, and place behind them. If your birth
          time is unknown and you accept the noon default, the reading will note that houses and
          time-sensitive placements are approximate.
        </p>
      </LegalSection>

      <LegalSection heading="Acceptable use">
        <p>
          Do not attempt to break, overload, or gain unauthorised access to the service; do not
          scrape it or resell its output as your own; do not submit another person's details without
          their agreement; and do not use it to harass anyone.
        </p>
      </LegalSection>

      <LegalSection heading="Content and ownership">
        <p>
          The software, design, and calculation engine remain ours. Your birth details remain yours,
          and the reading we prepare is yours to keep, print, and share.
        </p>
      </LegalSection>

      <LegalSection heading="Availability and liability">
        <p>
          The service is provided as-is. We do not promise it will be uninterrupted or error-free. To
          the extent the law allows, we are not liable for decisions you make based on a reading, or
          for indirect or consequential loss. Nothing here limits liability that cannot lawfully be
          limited.
        </p>
      </LegalSection>

      <LegalSection heading="Ending use">
        <p>
          You can stop using the service and request deletion of your data at any time by writing to{' '}
          <a href="mailto:hello@vedicsky.app">hello@vedicsky.app</a>. We may suspend access that
          breaches these terms.
        </p>
      </LegalSection>

      <LegalSection heading="Changes">
        <p>
          We may update these terms. The date at the top of this page shows when they last changed,
          and continuing to use the service after a change means you accept the new version.
        </p>
      </LegalSection>
    </LegalShell>
  );
}
