/** English copy — single locale for the gift funnel. Keys match config copyKeys. */
export const en = {
  'chooser.title': 'Choose your free reading',
  'chooser.subtitle':
    'Tell us a little about your birth sky. We prepare your report after you confirm your email.',
  'chooser.suggestion.title': 'Want something else?',
  'chooser.suggestion.help':
    'Describe the reading you wish we offered. Optional — we read every note.',
  'chooser.suggestion.placeholder': 'e.g. a relationship timing report…',
  'chooser.suggestion.emailLabel': 'Email (optional)',
  'chooser.suggestion.emailPlaceholder': 'you@example.com',
  'chooser.suggestion.submit': 'Send suggestion',
  'chooser.suggestion.thanks': 'Thank you — we received your note.',
  'chooser.suggestion.error': 'Could not send just now. Try again later.',
  'chooser.badge.new': 'New',

  'gifts.natal.name': 'Natal Code',
  'gifts.natal.description': 'Your birth chart — who you are and what you carry.',
  'gifts.natal.cta': 'Start Natal Code',
  'gifts.natal.note': '',

  'gifts.solar.name': 'Solar Code',
  'gifts.solar.description': 'Your year from birthday to birthday.',
  'gifts.solar.cta': 'Start Solar Code',
  'gifts.solar.note':
    'Available when your birthday falls within 30 days before or after today.',

  'gifts.annual.name': 'Annual Code',
  'gifts.annual.description': 'The next 12 months, month by month.',
  'gifts.annual.cta': 'Start Annual Code',
  'gifts.annual.note': '',

  'wizard.step1.title': 'Your birth details',
  'wizard.step1.subtitle': 'We use these to cast your chart. Take a moment — accuracy matters.',
  'wizard.step2.title': 'A little more context',
  'wizard.step2.subtitle':
    'Optional. Sharing this helps us shape the reading toward what matters to you.',
  'wizard.step3.title': 'Review and send',
  'wizard.step3.subtitle': 'Confirm everything looks right, then send your details.',
  'wizard.continue': 'Continue',
  'wizard.skipOptional': 'Skip — go to review',
  'wizard.back': 'Back',
  'wizard.editAnswers': 'Edit answers',
  'wizard.confirmSend': 'Send my details',
  // {privacy} and {terms} are replaced with links — keep both placeholders.
  'wizard.consent.label':
    'I agree to the {privacy} and {terms}. My data is kept until I request deletion.',
  'wizard.consent.privacy': 'Privacy Policy',
  'wizard.consent.terms': 'Terms of Service',
  'wizard.consent.error': 'Accept the Privacy Policy and Terms of Service to send your details.',
  'wizard.progress': 'Step {current} of {total}',
  'wizard.liveRegion': 'Step {current}: {title}',
  'wizard.unknownTime': "I don't know my birth time",
  'wizard.unknownTime.help': 'We will use noon (12:00) for your chart.',
  'wizard.review.birthInstant': 'Cast for {instant} UTC ({zone}).',
  'wizard.networkError': 'Connection failed. Your answers are still here — try again.',
  'wizard.retry': 'Try again',

  'fields.fullName.label': 'Full name',
  'fields.fullName.placeholder': 'As you would like it written',
  'fields.fullName.help': '',
  'fields.salutation.label': 'Salutation',
  'fields.salutation.placeholder': 'Choose one',
  'fields.salutation.help': '',
  'fields.birthDate.label': 'Birth date',
  'fields.birthDate.placeholder': '',
  'fields.birthDate.help': 'You must be 18 or older.',
  'fields.birthTime.label': 'Birth time',
  'fields.birthTime.placeholder': 'HH:MM',
  'fields.birthTime.help': '24-hour time as on your birth record.',
  'fields.birthPlace.label': 'Birth place',
  'fields.birthPlace.placeholder': 'Start typing a city…',
  'fields.birthPlace.help': 'Pick your city from the list so we can place your chart correctly.',
  'fields.celebrationPlace.label': 'Where you celebrate your birthday',
  'fields.celebrationPlace.placeholder': 'Start typing a city…',
  'fields.celebrationPlace.help': 'Pick from the list — your solar return is cast for this place.',
  'fields.place.resolved': '{lat}, {lon} · {zone}',
  'fields.email.label': 'Email',
  'fields.email.placeholder': 'you@example.com',
  'fields.email.help': 'We send your report link here.',
  'fields.emailConfirm.label': 'Confirm email',
  'fields.emailConfirm.placeholder': 'Type it again',
  'fields.emailConfirm.help': '',
  'fields.socialHandle.label': 'Social handle',
  'fields.socialHandle.placeholder': '@username',
  'fields.socialHandle.help': 'Optional.',
  'fields.interestArea.label': 'What interests you most',
  'fields.interestArea.placeholder': 'Choose one',
  'fields.interestArea.help': '',
  'fields.experienceLevel.label': 'Experience with astrology',
  'fields.experienceLevel.placeholder': 'Choose one',
  'fields.experienceLevel.help': '',
  'fields.relationshipStatus.label': 'Relationship status',
  'fields.relationshipStatus.placeholder': 'Choose one',
  'fields.relationshipStatus.help': '',
  'fields.childrenCount.label': 'Number of children',
  'fields.childrenCount.placeholder': '0',
  'fields.childrenCount.help': '',
  'fields.workStatus.label': 'Work status',
  'fields.workStatus.placeholder': 'Choose one',
  'fields.workStatus.help': '',
  'fields.occupation.label': 'Occupation',
  'fields.occupation.placeholder': 'What you do',
  'fields.occupation.help': '',
  'fields.freeNote.label': 'Anything else we should know',
  'fields.freeNote.placeholder': 'Optional note',
  'fields.freeNote.help': '',
  'fields.freeNote.counter': '{count} / 2000',

  'salutation.ms': 'Ms',
  'salutation.mrs': 'Mrs',
  'salutation.mr': 'Mr',
  'salutation.mx': 'Mx',
  'salutation.none': 'No salutation',

  'interest.self': 'Self-understanding',
  'interest.career': 'Career and purpose',
  'interest.relationships': 'Relationships',
  'interest.timing': 'Timing and cycles',
  'interest.spiritual': 'Spiritual path',

  'experience.new': 'New to this',
  'experience.some': 'Some familiarity',
  'experience.practiced': 'Practiced reader',

  'relationship.single': 'Single',
  'relationship.partnered': 'Partnered',
  'relationship.married': 'Married',
  'relationship.complicated': "It's complicated",
  'relationship.preferNot': 'Prefer not to say',

  'work.employed': 'Employed',
  'work.selfEmployed': 'Self-employed',
  'work.student': 'Student',
  'work.seeking': 'Seeking work',
  'work.other': 'Other',

  'errors.fullName': 'Enter a name between 2 and 100 characters.',
  'errors.salutation': 'Choose a salutation.',
  'errors.birthDate.invalid': 'Enter a valid birth date.',
  'errors.birthDate.future': 'Birth date cannot be in the future.',
  'errors.birthDate.ageMin': 'You must be at least 18 years old.',
  'errors.birthDate.ageMax': 'Enter a birth date that makes age 120 or under.',
  'errors.birthTime': 'Enter a valid time as HH:MM (24-hour).',
  'errors.place': 'Enter a place between 2 and 120 characters.',
  'errors.place.unresolved': 'Choose your city from the list so we can locate your chart.',
  'errors.email': 'Enter a valid email address.',
  'errors.emailConfirm': 'Confirm your email address.',
  'errors.emailConfirm.match': 'Email addresses must match.',
  'errors.childrenCount': 'Enter a whole number from 0 to 20.',
  'errors.freeNote': 'Keep your note under 2000 characters.',
  'errors.socialHandle': 'Keep your handle under 80 characters.',
  'errors.occupation': 'Keep occupation under 120 characters.',
  'errors.select': 'Choose one of the listed options.',
  'errors.generic': 'Check this field and try again.',

  'eligibility.title': 'Outside the Solar Code window',
  'eligibility.body':
    'Solar Code is for birthdays within 30 days before or after today. Natal Code is open now and uses the details you already entered.',
  'eligibility.accept': 'Continue with Natal Code',
  'eligibility.correct': 'Correct my birth date',

  'capacity.paused.title': 'Registrations are paused',
  'capacity.paused.body':
    'We have temporarily closed new gifts so we can prepare reports with care.',
  'capacity.paused.resume': 'We expect to reopen on {date}.',
  'capacity.paused.back': 'Back to gifts',

  'capacity.daily.title': "Today's gifts are spoken for",
  'capacity.daily.body':
    'Your answers are still saved in this tab. Come back tomorrow to send them.',
  'capacity.daily.cta': 'Back to gifts',

  'duplicate.title': 'This email is already registered',
  'duplicate.body':
    'We already have a request for this gift at {email}. Use a different email, or reach out if you need help.',
  'duplicate.different': 'Use a different email',
  'duplicate.contact': 'Contact us',

  'ceremony.beat1': 'Receiving your details',
  'ceremony.beat2': 'Securing your chart data',
  'ceremony.beat3': 'Preparing the email',
  'ceremony.beat4': 'Almost there',
  'ceremony.waiting': 'Still sending…',
  'ceremony.reduced': 'Sending your details…',

  'sent.title': 'Check your inbox',
  'sent.headline': 'Your report is created only after you click the link in the email.',
  'sent.body': 'We sent a confirmation to {email}. Open it and tap the link to continue.',
  'sent.spam': 'If you do not see it, check spam or promotions.',
  'sent.share': 'Know someone who would love a free reading?',
  'sent.back': 'Back to gifts',

  'share.whatsapp': 'WhatsApp',
  'share.viber': 'Viber',
  'share.facebook': 'Facebook',
  'share.telegram': 'Telegram',
  'share.copy': 'Copy link',
  'share.copied': 'Link copied',

  'verify.loading': 'Confirming your email…',
  'verify.ok.title': 'Email confirmed',
  'verify.ok.body': 'We are preparing your report. Watch your inbox for the finished reading.',
  'verify.ok.cta': 'Explore the app',
  'verify.expired.title': 'This link has expired',
  'verify.expired.body': 'Request the gift again and use the new email we send you.',
  'verify.expired.cta': 'Choose a gift',
  'verify.invalid.title': 'This link is not valid',
  'verify.invalid.body': 'It may already have been used, or the address was incomplete.',
  'verify.invalid.cta': 'Choose a gift',
  'verify.network.title': 'Could not reach the server',
  'verify.network.body': 'Check your connection, then open the email link again.',
  'verify.network.cta': 'Retry',

  'notFound.title': 'Gift not found',
  'notFound.body': 'That gift is not available. Pick one of the free readings below.',
  'notFound.cta': 'See gifts',

  'contact.href': 'mailto:hello@vedicsky.app',
} as const;

export type CopyKey = keyof typeof en;
